#!/bin/bash

{ rm autodeploy/insurance-crm-app-CURRENT-SNAPSHOT.ear || true ; } && cd ../../insurance/crm/ && mvn -DskipTests -Darguments=-DskipTests clean install && cd ../../eurasia36/deploy/ && mvn -Pautodeploy
